Repository Hirevo/alexandrie, pull requests merged in 2020-07, with the labels that each got.

#70 Improve documentation around setting up the crate index
  README.md
  docs/src/SUMMARY.md
  docs/src/getting-started.md
  docs/src/installation-script.md
Labels: C-documentation, M-deployment, P-high

#71 Changed E2E CI workflow to make use of job matrices
  .github/workflows/e2e.yaml
Labels: C-refactor, C-tests, P-medium

#76 Upgraded Rust version used for E2E tests to `1.44`
  Dockerfile
  e2e/images/runner/Dockerfile
Labels: C-tests, P-high

#74 Upgrade to Tide 0.12
  Cargo.lock
  alexandrie-index/Cargo.toml
  alexandrie-rendering/Cargo.toml
  alexandrie-storage/Cargo.toml
  alexandrie/Cargo.toml
  alexandrie/src/utils/auth/frontend.rs
  alexandrie/src/utils/cookies.rs
  alexandrie/src/utils/request_log.rs
Labels: C-dependencies, P-medium

#82 Fixed responses when errors are encountered
  alexandrie/src/main.rs
  alexandrie/src/utils/request_log.rs
Labels: C-bug, M-api, P-high

#77 Allow for more freedom for the server's binding address configuration
  alexandrie.toml
  alexandrie/src/config/mod.rs
  alexandrie/src/main.rs
  docker/mysql/alexandrie.toml
  docker/postgres/alexandrie.toml
  docker/sqlite/alexandrie.toml
Labels: C-enhancement, M-deployment, P-medium
