Repository Hirevo/alexandrie, pull requests merged in 2020-02, with the labels that each got.

#33 Removed defaults for creation and modification dates in database
  migrations/mysql/2019-10-12-193526_initialise/up.sql
  migrations/postgres/2019-10-12-193526_initialise/up.sql
  migrations/sqlite/2019-10-12-193526_initialise/up.sql
  src/api/publish.rs
  src/api/search.rs
  src/db/models.rs
  src/frontend/krate.rs
  src/frontend/last_updated.rs
  src/frontend/most_downloaded.rs
  src/frontend/search.rs
  src/index/models.rs
Labels: C-bug, P-high

#25 Support for crate badges
  migrations/mysql/2019-12-28-072041_badges/down.sql
  migrations/mysql/2019-12-28-072041_badges/up.sql
  migrations/postgres/2019-12-28-072041_badges/down.sql
  migrations/postgres/2019-12-28-072041_badges/up.sql
  migrations/sqlite/2019-12-28-072041_badges/down.sql
  migrations/sqlite/2019-12-28-072041_badges/up.sql
  src/api/publish.rs
  src/db/models.rs
  src/db/schema.rs
  src/frontend/krate.rs
  src/utils/rendering.rs
  syntect-themes/frontier-contrast.tmTheme
  templates/crate.hbs
Labels: C-enhancement, M-frontend, P-medium

#35 Added .dockerignore
  .dockerignore
Labels: C-enhancement, M-deployment, P-low
