Repository Hirevo/alexandrie, pull requests merged in 2020-04, with the labels that each got.

#40 refactor indexes
  src/api/publish.rs
  src/config/index/cli.rs
  src/index/cli.rs
  src/index/git2.rs
  src/index/mod.rs
  src/index/models.rs
  src/index/tree.rs
Labels: C-refactor

#38 Use 'as_deref'
  src/api/publish.rs
  src/frontend/account/login.rs
  src/frontend/account/register.rs
Labels: C-refactor, P-low

#31 Added separate `user` and `password_file` options in database configuration
  Cargo.lock
  Cargo.toml
  src/config/database.rs
  src/db/mod.rs
  src/main.rs
Labels: C-enhancement, P-high

#37 add test coverage CI and badge
  .github/workflows/coverage.yml
  Cargo.toml
Labels: C-tests

#47 Grammar fix in readme
  README.md
Labels: C-documentation

#49 Fixed missing dependency in Docker builds
  docker/mysql/Cargo.toml
  docker/postgresql/Cargo.toml
  docker/sqlite/Cargo.toml
  src/db/mod.rs
Labels: C-bug, P-high

#59 Fixed issue with missing fields in index records
  src/index/models.rs
Labels: C-bug, P-high

#61 Progress on the programmatic API
  src/api/account/login.rs
  src/api/account/mod.rs
  src/api/account/register.rs
  src/api/account/token/info.rs
  src/api/account/token/mod.rs
  src/api/account/token/revoke.rs
  src/api/crates/download.rs
  src/api/crates/info.rs
  src/api/crates/mod.rs
  src/api/crates/owners.rs
  src/api/crates/publish.rs
  src/api/crates/search.rs
  src/api/crates/unyank.rs
  src/api/crates/yank.rs
  src/api/mod.rs
  src/frontend/account/manage/tokens/mod.rs
  src/frontend/account/register.rs
  src/main.rs
  src/utils/auth.rs
Labels: C-enhancement, M-api, P-high

#62 End-to-End Testing
  .dockerignore
  .github/workflows/e2e.yaml
  Dockerfile
  README.md
  docker-compose.yaml
  docker/mysql/Cargo.toml
  docker/mysql/mysql-compose.yaml
  docker/postgres/alexandrie.toml
  docker/postgres/example.rootpass.txt
  docker/postgres/postgres-compose.yaml
  docker/postgresql/Cargo.toml
  docker/sqlite/Cargo.toml
  docker/startup.sh
  e2e/README.md
  e2e/images/.gitignore
  e2e/images/docker-compose.yaml
  e2e/images/gen-keys.sh
  e2e/images/index/init-repo.sh
  e2e/images/mysql-compose.yaml
  e2e/images/postgres-compose.yaml
  e2e/images/run-scenario.sh
  e2e/images/runner/Dockerfile
  e2e/images/runner/runner.sh
  e2e/scenarios/simple-library/runner.sh
  run_docker.sh
  src/main.rs
Labels: C-tests, P-high
