Repository Hirevo/alexandrie, pull requests merged in 2021-03, with the labels that each got.

#96 Hugo/fix error pg migrations
  .dockerignore
  docker/postgres/postgres-compose.yaml
  docker/startup.sh
  docs/src/whats-available/docker.md
Labels: C-bug, C-documentation, M-deployment, P-medium

#97 Make it possible to choose the UID/GID of the alex user
  docker-compose.yaml
  docs/src/whats-available/docker.md
Labels: C-documentation, C-enhancement, M-deployment, P-medium

#91 add build info with alexandrie.
  Cargo.lock
  README.md
  alexandrie/Cargo.toml
  alexandrie/build.rs
  alexandrie/src/main.rs
  alexandrie/src/utils/mod.rs
  alexandrie/src/utils/version.rs
Labels: C-enhancement, P-medium

#85 Removed a bunch of potentially unexpected panics
  alexandrie/src/frontend/account/login.rs
  alexandrie/src/frontend/account/manage/mod.rs
  alexandrie/src/frontend/account/manage/passwd.rs
  alexandrie/src/frontend/account/manage/tokens/mod.rs
  alexandrie/src/frontend/account/register.rs
  alexandrie/src/frontend/index.rs
  alexandrie/src/frontend/krate.rs
  alexandrie/src/frontend/last_updated.rs
  alexandrie/src/frontend/most_downloaded.rs
  alexandrie/src/frontend/search.rs
  alexandrie/src/main.rs
  alexandrie/src/utils/response/common.rs
  alexandrie/src/utils/response/mod.rs
Labels: C-bug, P-medium

#86 Refactor code to use the recently-stabilized slice patterns feature
  alexandrie/src/api/crates/owners.rs
Labels: C-refactor, P-low

#89 Added S3 storage documentation in user guide
  docs/src/whats-available/crate-stores.md
  docs/src/whats-available/mod.md
Labels: C-documentation, M-deployment, P-medium

#87 Re-organized code for setting up the server routes
  alexandrie/src/api/crates/download.rs
  alexandrie/src/config/frontend.rs
  alexandrie/src/main.rs
  alexandrie/src/utils/request_log.rs
  alexandrie/src/utils/response/mod.rs
Labels: C-refactor, P-medium

#105 General dependency upgrades
  Cargo.lock
  Dockerfile
  alexandrie-index/Cargo.toml
  alexandrie-rendering/Cargo.toml
  alexandrie-storage/Cargo.toml
  alexandrie/Cargo.toml
  alexandrie/build.rs
  alexandrie/src/api/account/token/info.rs
  alexandrie/src/api/crates/download.rs
  alexandrie/src/api/crates/info.rs
  alexandrie/src/api/crates/owners.rs
  alexandrie/src/api/crates/unyank.rs
  alexandrie/src/api/crates/yank.rs
  alexandrie/src/frontend/account/manage/tokens/revoke.rs
  alexandrie/src/frontend/krate.rs
  alexandrie/src/main.rs
  alexandrie/src/utils/build.rs
  alexandrie/src/utils/mod.rs
  alexandrie/src/utils/request_log.rs
  alexandrie/src/utils/version.rs
  e2e/images/runner/Dockerfile
Labels: C-dependencies, C-refactor, P-medium
