Repository Hirevo/alexandrie, pull requests merged in 2023-05, with the labels that each got.

#149 Fixed doc on GitLab auth
  docs/src/whats-available/authentication-strategies.md
Labels: C-documentation, P-medium, M-deployment

#154 Fixed legacy configuration in examples
  README.md
  docs/src/getting-started.md
Labels: C-documentation, P-low, M-deployment

#157 Fixed errors in `cargo owner` commands
  crates/alexandrie/src/api/crates/owners.rs
  docs/src/programmatic-api/crates/owners/delete.md
  docs/src/programmatic-api/crates/owners/put.md
  docs/src/programmatic-api/crates/unyank/put.md
  docs/src/programmatic-api/crates/yank/delete.md
Labels: C-bug, P-medium, M-api
