Repository Hirevo/alexandrie, pull requests merged in 2023-04, with the labels that each got.

#139 Bumped MSRV for CI runs to 1.68
  Dockerfile
  e2e/images/runner/Dockerfile
Labels: P-medium, C-tests, M-deployment

#117 External authentication methods
  .gitignore
  Cargo.lock
  alexandrie.toml
  crates/alexandrie/Cargo.toml
  crates/alexandrie/src/api/account/login.rs
  crates/alexandrie/src/api/account/register.rs
  crates/alexandrie/src/config/frontend/auth/github.rs
  crates/alexandrie/src/config/frontend/auth/gitlab.rs
  crates/alexandrie/src/config/frontend/auth/local.rs
  crates/alexandrie/src/config/frontend/auth/mod.rs
  crates/alexandrie/src/config/frontend/mod.rs
  crates/alexandrie/src/config/mod.rs
  crates/alexandrie/src/db/models.rs
  crates/alexandrie/src/db/schema.rs
  crates/alexandrie/src/error.rs
  crates/alexandrie/src/frontend/account/github/attach.rs
  crates/alexandrie/src/frontend/account/github/callback.rs
  crates/alexandrie/src/frontend/account/github/detach.rs
  crates/alexandrie/src/frontend/account/github/mod.rs
  crates/alexandrie/src/frontend/account/gitlab/attach.rs
  crates/alexandrie/src/frontend/account/gitlab/callback.rs
  crates/alexandrie/src/frontend/account/gitlab/detach.rs
  crates/alexandrie/src/frontend/account/gitlab/mod.rs
  crates/alexandrie/src/frontend/account/login.rs
  crates/alexandrie/src/frontend/account/manage/passwd.rs
  crates/alexandrie/src/frontend/account/mod.rs
  crates/alexandrie/src/frontend/account/register.rs
  crates/alexandrie/src/frontend/account/utils.rs
  crates/alexandrie/src/main.rs
  docker/mysql/alexandrie.toml
  docker/postgres/alexandrie.toml
  docker/sqlite/alexandrie.toml
  docs/src/SUMMARY.md
  docs/src/whats-available/authentication-strategies.md
  migrations/mysql/2021-10-12-215020_external_auth/down.sql
  migrations/mysql/2021-10-12-215020_external_auth/up.sql
  migrations/postgres/2021-10-12-215020_external_auth/down.sql
  migrations/postgres/2021-10-12-215020_external_auth/up.sql
  migrations/sqlite/2021-10-12-215020_external_auth/down.sql
  migrations/sqlite/2021-10-12-215020_external_auth/up.sql
  templates/account/login.hbs
  templates/account/manage.hbs
  templates/account/register.hbs
  templates/error.hbs
  templates/partials/head.hbs
Labels: C-enhancement, P-medium, M-frontend

#124 fix: check for compatible versions only
  crates/alexandrie-index/src/error.rs
  crates/alexandrie-index/src/tree.rs
  crates/alexandrie/src/api/crates/publish.rs
Labels: C-bug, P-medium, M-api

#123 fix: remove unused dependencies
  Cargo.lock
  crates/alexandrie-rendering/Cargo.toml
  crates/alexandrie/Cargo.toml
Labels: P-low, C-refactor

#142 Added MSRV CI check
  .github/workflows/ci.yaml
  .github/workflows/docs.yaml
  .github/workflows/e2e.yaml
  .github/workflows/formatting.yaml
  README.md
  crates/alexandrie/Cargo.toml
  docs/src/getting-started.md
  rust-toolchain.toml
Labels: C-documentation, P-medium, C-tests, M-deployment

#121 Fix: sessions table contains registered users only
  migrations/postgres/2022-09-18-221703_sessions-refactor-2/down.sql
  migrations/postgres/2022-09-18-221703_sessions-refactor-2/up.sql
Labels: C-bug, P-medium, M-frontend

#114 Add support for 'ssh://git@host:port/index.git' index URL syntax.
  docker/startup.sh
Labels: C-bug, C-enhancement, P-medium, M-deployment

#113 Include 's3' feature doc and link storage docs
  docs/src/concepts/crate-storage.md
  docs/src/whats-available/crate-stores.md
Labels: C-documentation, P-medium, M-deployment

#147 General dependency upgrades
  Cargo.lock
  crates/alexandrie-index/Cargo.toml
  crates/alexandrie-rendering/Cargo.toml
  crates/alexandrie-rendering/src/lib.rs
  crates/alexandrie-storage/Cargo.toml
  crates/alexandrie/Cargo.toml
  crates/alexandrie/src/api/crates/owners.rs
  crates/alexandrie/src/api/crates/publish.rs
  crates/alexandrie/src/db/database.rs
  crates/alexandrie/src/db/mod.rs
  crates/alexandrie/src/db/models.rs
  crates/alexandrie/src/error.rs
  crates/alexandrie/src/main.rs
  crates/alexandrie/src/utils/checks.rs
  helpers/syntect-dump/Cargo.toml
  syntect/dumps/syntaxes.dump
  syntect/dumps/themes.dump
  templates/account/manage.hbs
  templates/index.hbs
  templates/last-updated.hbs
  templates/most-downloaded.hbs
  templates/search.hbs
Labels: P-medium, M-frontend, M-api, C-refactor, C-dependencies
